### ISSUE TITLE
Email Server Should Download and Re-Upload Inline Images

### ISSUE THREAD

**Issue by neyre** [Team254/cheesy-mail#1]
Email messages sent from Gmail (like Matt's blog posts) are embedding images and hosting them on Google servers instead of adding them as attachments. Later, when these are posted on the blog, they sometimes don't display, and who knows how long they will stay hosted at the same URL. The desired behavior is probably for the email server to download all inline images and re-upload them to the Team 254 server, replacing the embed URLs along the way.

See below images not rendering:
https://www.team254.com/frc-day-4-build-blog/
![image](https://cloud.githubusercontent.com/assets/1348810/22030532/b978f210-dc92-11e6-80aa-57bd66d0e8e4.png)

**Comment by neyre** [comment]
@MarioRuiz18 @SuperMario210 can you go through the build blogs so far (or have a sub-team member help) and upload all the images to the Team website which are being embedded from Google?

**Comment by SuperMario210** [comment]
Sure.  I'll have a subteam member do that. I'll let you know when they are
finished.

**Comment by patfair** [comment]
I don't think this is Gmail's fault. I think Matt is editing the blog posts in Google Docs, then copy-pasting the whole thing into Gmail. The images were never embedded to begin with; they're <img> links from within Google Docs. The expiration issue is with the validity time period of those links.

**Comment by patfair** [comment]
The problem with the above approach is that not only will those images be broken on the blog, they'll also be broken if someone goes back and looks at the e-mails later from their e-mail client.

**Comment by neyre** [comment]
It might still be worth adding logic to download any embeds that aren't attached and re-embed. 

However, if Matt starts inserting images directly, the problem becomes much less urgent.

**Comment by neyre** [comment]
This is a continual problem. @patfair can we add this feature into the cheesy-mail server?

**Comment by neyre** [comment]
@patfair Can we do a round of upgrades on cheesy-mail and include this?

**Comment by SumiGovindaraju** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Cheesy Mail to automatically upload images](https://trello.com/c/szQJIlVx/2-fix-cheesy-mail-to-automatically-upload-images)
