### ISSUE TITLE
Send as @lists.team254.com address

### ISSUE THREAD

**Issue by neyre** [Team254/cheesy-mail#3]
(Adding this as an issue so that we don't forget about it)

We've had lots of issues lately with emails not going through, or just confusing users with multiple verification steps. We should modify the server so that no secondary verification is necessary, and the emails are consistently sent as a @lists.team254.com address. This will ensure that even emails from @bcp, @yahoo, etc make it through.

To make sure replys get back to the original sender, we can make the reply-to address <MEMBERID>@lists.team254.com and then put logic into the app to look up the email from the members server and forward those to the appropriate person.

**Comment by neyre** [comment]
This looks really good.

Can we make it so that the forwarded replies have reply-to headers that point back towards the person who sent the reply? The issue I could see us having now is that people get responses to their emails, and then reply to the responses, and we get the replies on the catch-all. Alternatively could just do the same encoded from address.

**Comment by patfair** [comment]
I considered that, but worried about having the same problem that we
originally did, where messages are bounced because SES doesn’t like the
reply-to address (and responders will likely have a wider variety). The
senders may just have to copy-paste the address.

**Comment by neyre** [comment]
Is there any reason not to just proxy replys to replys through the server with an encoded from address using the same code you already wrote?

**Comment by team254deployment** [comment]
I guess we could do that. I was envisioning that eventually the
conversation would shift into direct emailing back and forth, but there's
no real way to accomplish that without a working Reply-To or one of the
participants copy-pasting the address into the To: field. But allowing the
proxy to continue would be a reasonable fallback.
