### ISSUE TITLE
Post to Mattermost Chat with Webhook

### ISSUE THREAD

**Issue by neyre** [Team254/cheesy-mail#4]
Should be pretty easy to get it to post directly to the general channel with a webhook.
Documentation: https://docs.mattermost.com/developer/webhooks-incoming.html#simple-incoming-webhook

Markdown Template:
```
### <EMAIL SUBJECT>
_From <FROM NAME>_

<MESSAGE>
```

**Comment by SumiGovindaraju** [comment]
Sent email today that was sent (for sure) to the entire team. I don't know whether this was because it had the same exact subject line as a previous email, but it was not posted to #general by the bot.

**Comment by neyre** [comment]
Yeah, I got an error from the thing that cross-posts it. Ideally we can cut
out the middleman and have our mail server do it directly.

**Comment by SumiGovindaraju** [comment]
See if [this](https://github.com/Team254/cheesy-mail/pull/7) will work.

**Comment by SumiGovindaraju** [comment]
Integrated a bot. Will see if it works, after testing.

**Comment by neyre** [comment]
This works. Thanks, Sumi.
